# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Halcon\bias-ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 927)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.draw_multi = QtWidgets.QPushButton(self.centralwidget)
        self.draw_multi.setGeometry(QtCore.QRect(80, 140, 131, 51))
        self.draw_multi.setObjectName("draw_multi")
        self.path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.path_btn.setGeometry(QtCore.QRect(80, 20, 131, 51))
        self.path_btn.setStyleSheet("")
        self.path_btn.setObjectName("path_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 500, 621, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.figLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.figLayout2.setContentsMargins(0, 0, 0, 0)
        self.figLayout2.setObjectName("figLayout2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 20, 431, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(740, 20, 261, 851))
        self.textBrowser.setObjectName("textBrowser")
        self.draw_left = QtWidgets.QPushButton(self.centralwidget)
        self.draw_left.setGeometry(QtCore.QRect(80, 260, 131, 51))
        self.draw_left.setObjectName("draw_left")
        self.draw_right = QtWidgets.QPushButton(self.centralwidget)
        self.draw_right.setGeometry(QtCore.QRect(80, 380, 131, 51))
        self.draw_right.setObjectName("draw_right")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 100, 431, 371))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.figLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.figLayout1.setContentsMargins(0, 0, 0, 0)
        self.figLayout1.setObjectName("figLayout1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.path_btn.clicked.connect(MainWindow.mybutton)
        self.draw_multi.clicked.connect(MainWindow.draw_cmd)
        self.draw_left.clicked.connect(MainWindow.draw_cmd)
        self.draw_right.clicked.connect(MainWindow.draw_cmd)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "标定检测"))
        self.draw_multi.setText(_translate("MainWindow", "双目误差"))
        self.path_btn.setText(_translate("MainWindow", "文件夹选择"))
        self.draw_left.setText(_translate("MainWindow", "单目误差/左"))
        self.draw_right.setText(_translate("MainWindow", "单目误差/右"))
